In [16]:
#Author: Cameron R. Shabahang

#Generate a 10-year Duffie-Singleton model with the Ho-Lee model
#Compute 10 zero bond prices and a 10-year coupon bond price. Use the same parameter values. 
#Let the recovery be proportional to the otherwise undefaulted value
#At default, the recovery value is R = delta*Z(t,T)
#Z = price of zero coupon risky bond as if it has not defaulted
#Z(t,T) = Z(T,T)*exp((-r+s)(T-t))
#s = lam*(1-delta) = spread over the risk-free rate
#Z(T,T) is the terminal value = face value by assumption
#B(t,T) = sum(c*Z(t,Tj)+Z(t,Tn)
import pandas as pd
import numpy as np

r = 0.4 #Recovery rate
F = 100 #Par value
X_mul = [list(zip(x[0], x[1])) for x in [([k]*(k+1), list(np.arange(1,12,1))) for k in np.arange(1,11,1)]]
X_mul = [item for sublist in X_mul for item in sublist] #List comprehension to flatten
m_ind = pd.MultiIndex.from_tuples(X_mul) #Hierarchical indexing of list of tuples
DF_10 = pd.DataFrame(index = X_mul, columns = np.arange(1,12,1))
DF_10 = DF_10.reindex(m_ind)
DF_10 #Establish the empty dataframe 
#1 to 11 columns and ten hierarchies which have (1,2),(1,2,3) etc. to (1,...,11)

        1    2    3    4    5    6    7    8    9    10   11
1  1   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   2   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  1   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   2   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   3   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
10 7   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
   11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[65 rows x 11 columns]

In [ ]:
for i in range (1,11): #10yr Ho-Lee model
    DF_10.loc[i, i+1].iloc[:(i+1)] = [(0.96*F*0.04*F*0.4, F, F*0.4) for x in range (i+1)]
    for j in np.arange(i, 0, -1): 
        for k in np.arange(1, j+1,1): #Internal levels
            if j == 1: #Account for first level
                DF_10.loc[i,j][k] = 0.6*(DF_10.loc[i, j+1][k])[0]+0.4*((DF_10.loc[i, j+1][k+1]))
                *P.loc[0]
            else:
                y = (0.96*DF_10.loc[i, j+1][k][0])+0.4*DF_10.loc[i, j+1][k+1][0]*P.loc[j-1, j][k-1]
                x = 0.96*y+0.04*y*0.4 #B(t,T)
                DF_10.loc[i,j][k] = (x, y, y*0.4) #Implements recursion here
print(DF_10.iloc[10:])

In [10]:
print('zero-bond vs. coupon bond prices :')
print(P.loc[0,][0].iloc[1:]) #Coupon factor
print([DF_10.loc[x,1][1]/100 for x in range (1,11)]) #Zero bond prices
print([DF_10.loc[x,1][1]/100 for x in range (1,11)]/P.loc[0,][0].iloc[1:])

risk free vs risk :

NameError: name 'P' is not defined